/**
 * The apps' icon vocabulary: every icon a page may ask for, named for what
 * it means here rather than what Central Icons calls it. The components come
 * from src/generated (see README.md for adding one); a name ending in
 * `-fill` is the filled cut, which the console's rail and headers wear so
 * the way through the app reads heavier than the actions on a page.
 */
import {
  IconArrowBoxLeft,
  IconArrowLeft,
  IconArrowRight,
  IconArrowTriangleRight,
  IconBold,
  IconBuildings,
  IconBuildingsFilled,
  IconBulletList,
  IconCalendar1,
  IconCalendarClock,
  IconChainLink1,
  IconCheckmark1,
  IconChevronDownSmall,
  IconChevronLeftSmall,
  IconChevronRightSmall,
  IconCircleCheckFilled,
  IconCircleHalfFill,
  IconCircleX,
  IconClock,
  IconCode,
  IconCodeBrackets,
  IconCrossMedium,
  IconDotGrid1x3Horizontal,
  IconDotGrid2x3,
  IconDoubleCheckmark1,
  IconExclamationCircle,
  IconExclamationCircleFilled,
  IconExclamationTriangle,
  IconExclamationTriangleFilled,
  IconEyeOpen,
  IconFolder1,
  IconFormCircleFilled,
  IconFormDiamondFilled,
  IconFormOctagonFilled,
  IconGlobe,
  IconGroup1,
  IconGroup1Filled,
  IconHammer,
  IconHammerFilled,
  IconHistory,
  IconImac,
  IconItalic,
  IconLayersThree,
  IconLayersThreeFilled,
  IconLayoutDashboard,
  IconLayoutDashboardFilled,
  IconLightBulb,
  IconMagnifyingGlass,
  IconMaintenance,
  IconMaintenanceFilled,
  IconMoon,
  IconNumberedList,
  IconOpenQuote1,
  IconPaintBrush,
  IconPaintBrushFilled,
  IconPencil,
  IconPeople,
  IconPeopleFilled,
  IconPlusLarge,
  IconSettingsGear1,
  IconSettingsGear1Filled,
  IconSettingsSliderHor,
  IconSettingsSliderHorFilled,
  IconSiren,
  IconSirenFilled,
  IconSortArrowUpDown,
  IconSquareArrowTopRight,
  IconSquareArrowTopRightFilled,
  IconSun,
  IconTorch,
  IconTrashCan,
} from './generated/index.js';

export type { IconComponent, IconProps } from './generated/index.js';

export const icons = {
  // Actions
  add: IconPlusLarge,
  edit: IconPencil,
  delete: IconTrashCan,
  close: IconCrossMedium,
  'close-circle': IconCircleX,
  check: IconCheckmark1,
  'check-double': IconDoubleCheckmark1,
  play: IconArrowTriangleRight,
  more: IconDotGrid1x3Horizontal,
  'drag-handle': IconDotGrid2x3,
  search: IconMagnifyingGlass,
  'external-link': IconSquareArrowTopRight,
  'external-link-fill': IconSquareArrowTopRightFilled,
  'sign-out': IconArrowBoxLeft,

  // Direction
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  'chevron-left': IconChevronLeftSmall,
  'chevron-right': IconChevronRightSmall,
  'chevron-down': IconChevronDownSmall,
  'expand-up-down': IconSortArrowUpDown,

  // Places in the console
  dashboard: IconLayoutDashboard,
  'dashboard-fill': IconLayoutDashboardFilled,
  layers: IconLayersThree,
  'layers-fill': IconLayersThreeFilled,
  alert: IconExclamationTriangle,
  'alert-fill': IconExclamationTriangleFilled,
  hammer: IconHammer,
  'hammer-fill': IconHammerFilled,
  settings: IconSettingsGear1,
  'settings-fill': IconSettingsGear1Filled,
  user: IconPeople,
  'user-fill': IconPeopleFilled,
  group: IconGroup1,
  'group-fill': IconGroup1Filled,
  building: IconBuildings,
  'building-fill': IconBuildingsFilled,
  brush: IconPaintBrush,
  'brush-fill': IconPaintBrushFilled,
  sliders: IconSettingsSliderHor,
  'sliders-fill': IconSettingsSliderHorFilled,
  folder: IconFolder1,
  flashlight: IconTorch,
  history: IconHistory,

  // Time
  time: IconClock,
  'time-zone': IconGlobe,
  calendar: IconCalendar1,
  'calendar-event': IconCalendarClock,

  // Appearance
  sun: IconSun,
  moon: IconMoon,
  computer: IconImac,
  contrast: IconCircleHalfFill,

  // Status marks: the filled shapes a service's status wears (status.ts)
  'circle-check-fill': IconCircleCheckFilled,
  'diamond-fill': IconFormDiamondFilled,
  'triangle-fill': IconExclamationTriangleFilled,
  'octagon-fill': IconFormOctagonFilled,
  'tools-fill': IconMaintenanceFilled,
  'circle-fill': IconFormCircleFilled,

  // Phases
  lightbulb: IconLightBulb,
  eye: IconEyeOpen,
  tools: IconMaintenance,

  // Impact: the warning signs it escalates through, solid like the status marks
  'error-warning': IconExclamationCircle,
  'error-warning-fill': IconExclamationCircleFilled,
  siren: IconSiren,
  'siren-fill': IconSirenFilled,

  // Rich text
  bold: IconBold,
  italic: IconItalic,
  code: IconCode,
  'code-block': IconCodeBrackets,
  link: IconChainLink1,
  'list-bullets': IconBulletList,
  'list-numbered': IconNumberedList,
  quote: IconOpenQuote1,
} as const;

export type IconName = keyof typeof icons;
